### ISSUE TITLE
Action leaks temporary token

### ISSUE THREAD

**Issue by marksteward** [Lewuathe/dropbox-github-action#4]
Hi, this action leaks the temporary token as it's passed into the environment for the `upload-file` step. You probably want to do something like [this](https://github.com/marksteward/inspire-polygons/blob/main/.github/workflows/boundaries.yml#L27-L43) instead:

```
          echo "::add-mask::$token"
          echo "token=$token" >> "$GITHUB_OUTPUT"
...
            -H "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
```

See also https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-masking-a-generated-output-within-a-single-job

**Comment by marksteward** [comment]
Hi, this is a security issue, do I need to get in touch with GitHub directly?

**Comment by Lewuathe** [comment]
@marksteward Sorry, I missed your comment here and thanks for reporting. You are right. I think we need to deal with the issue ASAP. I created a fix for this problem as follows.

https://github.com/Lewuathe/dropbox-github-action/pull/5

**Comment by Lewuathe** [comment]
I have updated the v1 tag to include the latest fix. 

https://github.com/Lewuathe/dropbox-github-action/tree/v1

**Comment by marksteward** [comment]
I'm afraid that doesn't fix it, because you're still passing the token via the environment. Please use the code I've provided above.

**Comment by Lewuathe** [comment]
@marksteward Thanks for pointing out. That's true. I tried to fix the issue here. 
https://github.com/Lewuathe/dropbox-github-action/pull/6

**Comment by marksteward** [comment]
Can I suggest you update the v1 tag as well, or at least remove that version and v1.0.1 so that any actions relying on it break?

**Comment by Lewuathe** [comment]
@marksteward I updated the v1 tag too so that all actions using this plugin should use the latest fix.

https://github.com/Lewuathe/dropbox-github-action/tree/v1

**Comment by marksteward** [comment]
Looks good, thanks for that!
